config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins
  resources :constituencies
  resources :wards  do
    resources :projects
  end
  resources :institutions do
    resources :collections
  end
  resources :students
  resources :busaries do
    collection do
      post :import
      get :disbursment
    end
  end
  resources :financial_years

  # lannding page
  root 'constituencies#index'

  # custom routes
  get 'analytics', :to => 'busaries#analytics', :as => :analytics
  get 'award/:id', :to => 'busaries#award', :as => :award

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
  require 'activerecord-import'
end

app/models/busary.rb
class Busary < ApplicationRecord
  belongs_to :student
  belongs_to :institution
  has_one :financial_year
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :institution
  belongs_to :financial_year
end

app/models/constituency.rb
class Constituency < ApplicationRecord
  has_one :image
end

app/models/county.rb
class County < ApplicationRecord
  has_many :institutions
end

app/models/disbursment.rb
class Disbursment < ApplicationRecord
  has_one :financial_year

  def self.import_file(file)
    records = CSV.foreach(file.path, headers: true, :encoding => 'ISO-8859-1').map { |col| Hash[institution_name: col[0], student_name: col[1], reg_no: col[2], level: col[3], amount: col[4]
] }
    r = []
    records.each do |rec|
      if rec[:institution_name] != nil && rec[:amount] != nil && rec[:student_name] != nil
        rec[:amount] = rec[:amount].gsub(/[^\d\.]/, '').to_d
        r << rec
      end
    end
    Disbursment.import r
  end


end

app/models/financial_year.rb
class FinancialYear < ApplicationRecord
  has_many :disbursments, dependent: :destroy
  has_many :busaries
  has_many :collections
  has_many :projects
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :project
  belongs_to :constituency
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :students
  has_many :busaries
  belongs_to :county
  belongs_to :school_type
  has_many :collections
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :ward
  has_many :images
  belongs_to :financial_year
end

app/models/school_type.rb
class SchoolType < ApplicationRecord
  has_many :institutions
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :busaries
  belongs_to :institution

  def self.search(search)
    if search
      where('surname LIKE ?', "%#{search}%")
    else
      Student.all
    end
  end

end

app/models/ward.rb
class Ward < ApplicationRecord
  has_many :projects
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  # GET /students
  # GET /students.json
  def index
    @students = Student.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 100, :page => params[:page])
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @busaries = Busary.where(student_id: params[:id]).paginate(:per_page => 5, :page => params[:page])
    @collected = @busaries.where(status: true)
    @sum_collected = 0
    @collected.each do |sum|
      @sum_collected += sum.amount
    end
    # sum total of busaries issued
    @sum_total = 0
    @busaries.each do |sum|
      @sum_total += sum.amount
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # default sort
    def sort_column
      params[:sort] || "first_name"
    end

    def sort_direction
      params[:direction] || "asc"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :middle_name, :surname, :reg_no, :level, :institution_id, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# sorting tabe helper_method
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end


end

app/helpers/busaries_helper.rb
module BusariesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/import_files_helper.rb
module ImportFilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :student_first_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, id: :student_middle_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :student_surname %>
  </div>

  <div class="field">
    <%= form.label :reg_no %>
    <%= form.text_field :reg_no, id: :student_reg_no %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :student_level %>
  </div>

  <div class="field">
    <%= form.label :institution_id %>
    <%= form.collection_select :institution_id, Institution.all, :id, :name, {prompt: "Select Institution"}, class: "browser-default" %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :student_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_students.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @students %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>
<%= form_tag students_path, :method => 'get', :id => "students_search" do %>
  <p>
    <label>Search Students by Surname</label>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", class: 'btn' %>
  </p>

  <div id="students">
    <%= render 'students' %>
  </div>
<% end %>


<table>
  <thead>
    <tr>
      <th>Names</th>
      <th>Reg no</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %>
          <%= student.middle_name %>
          <%= student.surname %>
        </td>
        <td><%= student.reg_no %></td>
        <td><%= student.level %></td>
        <td><%= link_to 'Show', student, class: 'btn' %></td>
        <% if admin_signed_in? %>
          <td><%= link_to 'Edit', edit_student_path(student), class: 'btn yellow lighten-2' %></td>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn red lighten-2' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @students %>

<br>
<% if admin_signed_in? %>
  <%= link_to 'New Student', new_student_path, class: "btn" %>
<% end %>

app/views/students/index.js.erb
$("#students").html("<%= j render 'students' %>");

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_student_path(@student), class: "btn" %>
  <%= link_to 'Back', students_path, class: "btn" %>
  <%= link_to 'Issue Busary', new_busary_path(student_id: @student), class: "btn" %>
<% end %>
<h2><%= @student.first_name %> <%= @student.middle_name %> <%= @student.surname %></h2>
<p><strong>Institution:</strong> <%= link_to @student.institution.name, institution_path(@student.institution) %></p>
<p><strong>Registration Number:</strong> <%= @student.reg_no %></p>
<p><strong>Total Busaries:</strong> <%= number_to_currency(@sum_total, unit: "Ksh", separator: ".", delimiter: ",") %> </p>
<p><strong>Collected Busaries:</strong> <%= number_to_currency(@sum_collected, unit: "Ksh", separator: ".", delimiter: ",") %> </p>
<p><strong>Notes:</strong> <%= @student.notes %> </p>

<h3>Busaries (<%= @busaries.count %>)</h3>
<% if @busaries.any? %>
<table>
  <th>Financial Year</th>
  <th>Collected</th>
  <th>Amount</th>
  <tbody>
    <% @busaries.each do |busary| %>
        <tr>
          <td><%= FinancialYear.find(busary.financial_year_id).f_year %></td>
          <% if busary.status === true %>
            <td><label class="badge green">Collected</label></td>
          <% else %>
            <% if admin_signed_in? %>
              <td><label class="badge red"><%= link_to "Award", award_path(busary.id), style: "color: white;" %></label></td>
            <% else %>
                <td><label class="badge yellow">Pending</label></td>
            <% end %>
          <% end %>
          <td><%= number_to_currency(busary.amount, unit: "Ksh", separator: ".", delimiter: ",") %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @busaries %>

<% end %>