config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins
  resources :constituencies
  resources :wards  do
    resources :projects
  end
  resources :institutions do
    resources :collections
  end
  resources :students
  resources :busaries do
    collection do
      post :import
      get :disbursment
    end
  end
  resources :financial_years

  # lannding page
  root 'constituencies#index'

  # custom routes
  get 'analytics', :to => 'busaries#analytics', :as => :analytics
  get 'award/:id', :to => 'busaries#award', :as => :award

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
  require 'activerecord-import'
end

app/models/busary.rb
class Busary < ApplicationRecord
  belongs_to :student
  belongs_to :institution
  has_one :financial_year
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :institution
  belongs_to :financial_year
end

app/models/constituency.rb
class Constituency < ApplicationRecord
  has_one :image
end

app/models/county.rb
class County < ApplicationRecord
  has_many :institutions
end

app/models/disbursment.rb
class Disbursment < ApplicationRecord
  has_one :financial_year

  def self.import_file(file)
    records = CSV.foreach(file.path, headers: true, :encoding => 'ISO-8859-1').map { |col| Hash[institution_name: col[0], student_name: col[1], reg_no: col[2], level: col[3], amount: col[4]
] }
    r = []
    records.each do |rec|
      if rec[:institution_name] != nil && rec[:amount] != nil && rec[:student_name] != nil
        rec[:amount] = rec[:amount].gsub(/[^\d\.]/, '').to_d
        r << rec
      end
    end
    Disbursment.import r
  end


end

app/models/financial_year.rb
class FinancialYear < ApplicationRecord
  has_many :disbursments, dependent: :destroy
  has_many :busaries
  has_many :collections
  has_many :projects
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :project
  belongs_to :constituency
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :students
  has_many :busaries
  belongs_to :county
  belongs_to :school_type
  has_many :collections
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :ward
  has_many :images
  belongs_to :financial_year
end

app/models/school_type.rb
class SchoolType < ApplicationRecord
  has_many :institutions
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :busaries
  belongs_to :institution

  def self.search(search)
    if search
      where('surname LIKE ?', "%#{search}%")
    else
      Student.all
    end
  end

end

app/models/ward.rb
class Ward < ApplicationRecord
  has_many :projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.ward_id = params[:ward_id]
    @ward = Ward.find(params[:ward_id])
    respond_to do |format|
      if @project.save
        format.html { redirect_to @ward, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :ward_id, :financial_year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# sorting tabe helper_method
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end


end

app/helpers/busaries_helper.rb
module BusariesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/import_files_helper.rb
module ImportFilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, url: ward_projects_path, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :project_description %>
  </div>
  <!-- Add project to financial year -->
  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: 'datepicker' %>

  </div>

  <div class="actions">
    <%= form.submit 'Create', class: 'btn lighten-2' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.ward_id %></td>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', ward_projects_path, class: 'btn lighten-2' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <% if admin_signed_in? %>
  <%= link_to 'Edit', edit_ward_project_path(@project), class: "btn" %>
  <%= link_to 'Uplaod Images', new_image_path(@project), class: "btn" %>
  <% end %>
  <%= link_to 'Back', ward_path(@project.ward_id), class: "btn" %>

</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
<!-- List project photos and any other desc -->
<div class="row">
       <% @project.images.each do |image| %>
       <div class="col s4">
         <div class="card">
           <div class="card-image">
             <%= image_tag image.image.url, class: "screen-img" %>
           </div>
           <div class="card-content">
             <p><%= image.description %></p>
             </div>
          </div>
        </div>
       <% end %>
   </div>