config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins
  resources :constituencies
  resources :wards  do
    resources :projects
  end
  resources :institutions do
    resources :collections
  end
  resources :students
  resources :busaries do
    collection do
      post :import
      get :disbursment
    end
  end
  resources :financial_years

  # lannding page
  root 'constituencies#index'

  # custom routes
  get 'analytics', :to => 'busaries#analytics', :as => :analytics
  get 'award/:id', :to => 'busaries#award', :as => :award

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
  require 'activerecord-import'
end

app/models/busary.rb
class Busary < ApplicationRecord
  belongs_to :student
  belongs_to :institution
  has_one :financial_year
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :institution
  belongs_to :financial_year
end

app/models/constituency.rb
class Constituency < ApplicationRecord
  has_one :image
end

app/models/county.rb
class County < ApplicationRecord
  has_many :institutions
end

app/models/disbursment.rb
class Disbursment < ApplicationRecord
  has_one :financial_year

  def self.import_file(file)
    records = CSV.foreach(file.path, headers: true, :encoding => 'ISO-8859-1').map { |col| Hash[institution_name: col[0], student_name: col[1], reg_no: col[2], level: col[3], amount: col[4]
] }
    r = []
    records.each do |rec|
      if rec[:institution_name] != nil && rec[:amount] != nil && rec[:student_name] != nil
        rec[:amount] = rec[:amount].gsub(/[^\d\.]/, '').to_d
        r << rec
      end
    end
    Disbursment.import r
  end


end

app/models/financial_year.rb
class FinancialYear < ApplicationRecord
  has_many :disbursments, dependent: :destroy
  has_many :busaries
  has_many :collections
  has_many :projects
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :project
  belongs_to :constituency
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :students
  has_many :busaries
  belongs_to :county
  belongs_to :school_type
  has_many :collections
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :ward
  has_many :images
  belongs_to :financial_year
end

app/models/school_type.rb
class SchoolType < ApplicationRecord
  has_many :institutions
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :busaries
  belongs_to :institution

  def self.search(search)
    if search
      where('surname LIKE ?', "%#{search}%")
    else
      Student.all
    end
  end

end

app/models/ward.rb
class Ward < ApplicationRecord
  has_many :projects
end

app/controllers/busaries_controller.rb
class BusariesController < ApplicationController
  before_action :set_busary, only: [:show, :edit, :update, :destroy, :award]

  # GET /busaries
  # GET /busaries.json

  def import
    Disbursment.import_file(params[:file])
    redirect_to disbursment_busaries_path, notice: "Busaries Imported"
  end

  def disbursment
    @disbursments = Disbursment.where(financial_year_id: nil)
    @financial_years = FinancialYear.all
  end

  def index
    @students = Student.all
    @institutions = Institution.all
    @busaries = Busary.all
    @sum_total = 0
    @busaries.each { |busary| @sum_total += busary.amount  }
  end

  # GET /busaries/1
  # GET /busaries/1.json
  def show
    
  end

  def analytics

  end

  def award
    @busary.update(status: true, issue_date: Date.today)
    @student = @busary.student
    redirect_to @student, notice: 'Busary Awarded'
  end

  # GET /busaries/new
  def new
    @busary = Busary.new
  end

  # GET /busaries/1/edit
  def edit
  end

  # POST /busaries
  # POST /busaries.json
  def create
    @busary = Busary.new(busary_params)
    @student = Student.find(busary_params[:student_id])

    respond_to do |format|
      if @busary.save
        format.html { redirect_to @student, notice: 'Busary was successfully created.' }
        format.json { render :show, status: :created, location: @busary }
      else
        format.html { render :new }
        format.json { render json: @busary.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /busaries/1
  # PATCH/PUT /busaries/1.json
  def update
    respond_to do |format|
      if @busary.update(busary_params)
        format.html { redirect_to @busary, notice: 'Busary was successfully updated.' }
        format.json { render :show, status: :ok, location: @busary }
      else
        format.html { render :edit }
        format.json { render json: @busary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busaries/1
  # DELETE /busaries/1.json
  def destroy
    @busary.destroy
    respond_to do |format|
      format.html { redirect_to busaries_url, notice: 'Busary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busary
      @busary = Busary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def busary_params
      params.require(:busary).permit(:amount, :status, :student_id, :institution_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# sorting tabe helper_method
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end


end

app/helpers/busaries_helper.rb
module BusariesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/import_files_helper.rb
module ImportFilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/busaries/_form.html.erb
<%= form_with(model: busary, local: true) do |form| %>
  <% if busary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(busary.errors.count, "error") %> prohibited this busary from being saved:</h2>

      <ul>
      <% busary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :student_id, value: params[:student_id] %>
  </div>

  <div class="field">
    <%= form.hidden_field :institution_id, value: Student.find(params[:student_id]).institution_id %>
  </div>
  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :busary_amount %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :busary_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/busaries/analytics.html.erb
<h2>Trends and Analytics</h2>

<div class="row">
  <div class="col s4">
    <p>Allocation by Year</p>
    <%= pie_chart({"2013" => 10, "2014" => 5, "2015" => 5, "2016" => 5, "2017" => 5}, download: true) %>
  </div>
  <div class="col s4">
    <p>Boarding vs Day Schools</p>
    <%= pie_chart({"Day Schools" => 10, "Boarding Schools" => 5}) %>
  </div>
  <div class="col s4">
    <p>By Level of Education</p>
    <%= pie_chart({"Universitis" => 10, "High Schools" => 5, "Primary School" => 5}) %>
  </div>
  <div class="col s4">
    <p>Boy vs Girls</p>
    <%= pie_chart({"Boys" => 10, "Girls" => 15}) %>
  </div>

</div>

app/views/busaries/disbursment.html.erb
<% @financial_years.each do |fy| %>
  <button class="btn" onclick="financial_year(<%= fy.id %>)"><%= fy.f_year %></button>
  
<% end %>

<% @financial_years.each do |fy| %>
<div id="financial_year<%= fy.id %>" style="display: none">
    <div class="dash">
      <p> <strong>Total Disbursed:</strong> <%= number_to_currency(fy.disbursments.sum(:amount), unit: "KES ") %> </p>
      <p> <strong>Institutions: </strong> <%= fy.disbursments.select(:institution_name).map(&:institution_name).uniq.count %> </p>
      <p> <strong>Students: </strong> <%= fy.disbursments.count %> </p>
    </div>
    <div class="row">
      <div class="col s6">
        <h3>Institutions</h3>
        <table class="striped">
          <thead>
            <th>Institution</th>
            <th>No. Students</th>
            <th>Total Allocation</th>
          </thead>
          <tbody>
            <% fy.disbursments.select(:institution_name).map(&:institution_name).uniq.each do |inst| %>
              <tr>
                <td><%= inst %> </td>
                <td><%= fy.disbursments.where("institution_name =?", inst).count %> </li></td>
                <td><%= fy.disbursments.where("institution_name =?", inst).sum(:amount) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col s6">
        <h3>Beneficieries</h3>
        <table class="striped">
          <thead>
            <th>Institution Name</th>
            <th>Student Name</th>
            <th>Registration Number</th>
            <th>Class</th>
            <th>Amount</th>
            <th>Financial Year</th>
          </thead>
          <tbody>
            <% fy.disbursments.each do |disbursment| %>
              <tr>
                <td><%= disbursment.institution_name %></td>
                <td><%= disbursment.student_name %></td>
                <td><%= disbursment.reg_no %></td>
                <td><%= disbursment.level %></td>
                <td><%= disbursment.amount %></td>
                <td><%= if disbursment.financial_year_id != nil  then FinancialYear.find(disbursment.financial_year_id).f_year end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <% end %>


<h1>New Busary Disbursments</h1>
<%= form_tag financial_years_path do  %>
  <div class="field">
    <label for="">Enter Financial Year</label>
    <%= text_field_tag :f_year %>
  </div>
  <%= submit_tag 'Save Disbursment' %>
<% end %>
<table class="striped">
  <thead>
    <th>Institution Name</th>
    <th>Student Name</th>
    <th>Registration Number</th>
    <th>Class</th>
    <th>Amount</th>
  </thead>
  <tbody>
    <% @disbursments.each do |disbursment| %>
      <tr>
        <td><%= disbursment.institution_name %></td>
        <td><%= disbursment.student_name %></td>
        <td><%= disbursment.reg_no %></td>
        <td><%= disbursment.level %></td>
        <td><%= disbursment.amount %></td>
        <td><%= if disbursment.financial_year_id != nil  then FinancialYear.find(disbursment.financial_year_id).f_year end %></td>
      </tr>
    <% end %>
    <p> <strong>Total: <%= number_to_currency( @disbursments.sum(:amount), unit: 'KES ' ) %></strong> </p>
  </tbody>
</table>

app/views/busaries/edit.html.erb
<h1>Editing Busary</h1>

<%= render 'form', busary: @busary %>

<%= link_to 'Show', @busary %> |
<%= link_to 'Back', busaries_path %>

app/views/busaries/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Busary Application</h3>

<div class="row">
  <div class="col s4">
    <% if admin_signed_in? %>
      <%= link_to 'Students', students_path, class: 'btn' %>
      <%= link_to 'Add Student', new_student_path, class: 'btn' %>
    <% else %>
      <%= link_to 'Students', students_path, class: 'btn' %>
    <% end %>
    <p><%= number_to_currency(@sum_total, :unit => "Ksh" ) %> issued in busary cheques</p>
    <p>We have <%= @students.count %> under the busary program</p>
    <p>Some Other relavant informatio can go here</p>
    <p>Like the amount of time it take sfor busaries to get ready</p>
  </div>

  <div class="col s4">
    <% if admin_signed_in? %>
      <%= link_to 'Institutions', institutions_path, class: 'btn' %>
      <%= link_to 'Add Institute', new_institution_path %>
    <% else %>
      <%= link_to 'Institutions', institutions_path, class: 'btn' %>
    <% end %>
    <p>Busaries have been disbursed to <%= @institutions.count %> institutions
       all over the country.
    </p>
  </div>

  <div class="col s4">
    <%= link_to 'Disbursments', disbursment_busaries_path, class: 'btn' %>
    <% if admin_signed_in? %>
      <%= form_tag import_busaries_path, multipart: true do %>
        <div class="field">
          <%= file_field_tag :file %>
        </div>
        <%= submit_tag "Import", class: 'btn' %>
      <% end %>
    <% end %>
  </div>



</div>

app/views/busaries/new.html.erb
<h1>New Busary</h1>

<%= render 'form', busary: @busary %>

<%= link_to 'Back', busaries_path %>

app/views/busaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @busary.amount %>
</p>

<p>
  <strong>Status:</strong>
  <%= @busary.status %>
</p>

<%= link_to 'Edit', edit_busary_path(@busary) %> |
<%= link_to 'Back', busaries_path %>