config/routes.rb
Rails.application.routes.draw do
  resources :images
  devise_for :admins
  resources :constituencies
  resources :wards  do
    resources :projects
  end
  resources :institutions do
    resources :collections
  end
  resources :students
  resources :busaries do
    collection do
      post :import
      get :disbursment
    end
  end
  resources :financial_years

  # lannding page
  root 'constituencies#index'

  # custom routes
  get 'analytics', :to => 'busaries#analytics', :as => :analytics
  get 'award/:id', :to => 'busaries#award', :as => :award

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
  require 'activerecord-import'
end

app/models/busary.rb
class Busary < ApplicationRecord
  belongs_to :student
  belongs_to :institution
  has_one :financial_year
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :institution
  belongs_to :financial_year
end

app/models/constituency.rb
class Constituency < ApplicationRecord
  has_one :image
end

app/models/county.rb
class County < ApplicationRecord
  has_many :institutions
end

app/models/disbursment.rb
class Disbursment < ApplicationRecord
  has_one :financial_year

  def self.import_file(file)
    records = CSV.foreach(file.path, headers: true, :encoding => 'ISO-8859-1').map { |col| Hash[institution_name: col[0], student_name: col[1], reg_no: col[2], level: col[3], amount: col[4]
] }
    r = []
    records.each do |rec|
      if rec[:institution_name] != nil && rec[:amount] != nil && rec[:student_name] != nil
        rec[:amount] = rec[:amount].gsub(/[^\d\.]/, '').to_d
        r << rec
      end
    end
    Disbursment.import r
  end


end

app/models/financial_year.rb
class FinancialYear < ApplicationRecord
  has_many :disbursments, dependent: :destroy
  has_many :busaries
  has_many :collections
  has_many :projects
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :project
  belongs_to :constituency
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :students
  has_many :busaries
  belongs_to :county
  belongs_to :school_type
  has_many :collections
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :ward
  has_many :images
  belongs_to :financial_year
end

app/models/school_type.rb
class SchoolType < ApplicationRecord
  has_many :institutions
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :busaries
  belongs_to :institution

  def self.search(search)
    if search
      where('surname LIKE ?', "%#{search}%")
    else
      Student.all
    end
  end

end

app/models/ward.rb
class Ward < ApplicationRecord
  has_many :projects
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  require 'pry'
  before_action :set_ward, only: [:show, :edit, :update, :destroy]

  # GET /wards
  # GET /wards.json

  def index
    @wards = Ward.all
    @years = FinancialYear.all

  end

  # GET /wards/1
  # GET /wards/1.json
  def show
    # Get projects
    @projects = Project.where(ward_id: params[:id])
    # Four financial years

  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to @ward, notice: 'Ward was successfully created.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to @ward, notice: 'Ward was successfully updated.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to wards_url, notice: 'Ward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ward_params
      params.require(:ward).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# sorting tabe helper_method
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end


end

app/helpers/busaries_helper.rb
module BusariesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/import_files_helper.rb
module ImportFilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/wards_helper.rb
module WardsHelper
end

app/views/wards/_form.html.erb
<%= form_with(model: ward, local: true) do |form| %>
  <% if ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
      <% ward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ward_name %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :ward_description %>
  </div>

  <div class="actions">
    <%= form.submit 'Create', class: 'btn lighten-2' %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<h1>Editing Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Show', @ward %> |
<%= link_to 'Back', wards_path %>

app/views/wards/financial_year.html.erb
<ul>
  <li>2013/14</li>
  <li>2014/15</li>
  <li>2015/16</li>
  <li>2016/17</li>
</ul>

app/views/wards/index.html.erb
<p id="notice"><%= notice %></p>

  <h6>Financial Years</h6>
  <% @years.each do |year| %>
    <button class="btn lighten-2"><%= year.f_year %></button>
  <% end %>

<h1>Wards</h1>
  <% if admin_signed_in? %>
    <%= link_to 'New Ward', new_ward_path, class: 'btn' %>
  <% end %>
  <div class="row">
    <% @wards.each do |ward| %>
    <div class="col s3">
      <div class="card">
         <div class="card-image waves-effect waves-block waves-light">
            <%= image_tag('flag2.jpg', class: 'activator') %>
         </div>
         <div class="card-content">
           <%= link_to ward.name, ward, class: 'btn' %>
         </div>
        </div>
    </div>

    <% end %>
  </div>

app/views/wards/new.html.erb
<h1>New Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Back', wards_path, class: 'btn lighten-2' %>

app/views/wards/show.html.erb
<p id="notice"><%= notice %></p>
<% if admin_signed_in? %>
  <%= link_to 'Add Project',  new_ward_project_path(@ward), class: "btn" %>
<% end %>
  <h1><%= @ward.name %></h1>
  <p><%= @ward.description %></p>

  <div class="row">
    <% @ward.projects.each do |project| %>
    <div class="col s6">
      <div class="card">
         <div class="card-image waves-effect waves-block waves-light">
           <!-- image_tag project.images.first.id -->
            <% if project.images.any? %>
              <%= image_tag project.images.first.image.url, class: "screen-img" %>
            <% else %>
              <%= image_tag("flag2.jpg") %>
            <% end %>
         </div>
         <div class="card-content">
           <%= link_to project.name, ward_project_path(@ward,project), class: "btn" %>
         </div>
        </div>
    </div>

    <% end %>
  </div>


<% if admin_signed_in?%>
  <%= link_to 'Edit', edit_ward_path(@ward), class: "btn" %>
<% end %>
<%= link_to 'Back', wards_path, class: "btn" %>